/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-10-24 05:47:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import mango.mango.model.MemberVO;

public final class askForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(12);
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar!/META-INF/taglib.tld", Long.valueOf(1539665194000L));
    _jspx_dependants.put("/WEB-INF/views/taglib.jsp", Long.valueOf(1659599458555L));
    _jspx_dependants.put("/WEB-INF/lib/egovframework.rte.ptl.mvc-3.8.0.jar", Long.valueOf(1663548654023L));
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1523252374000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1654653023355L));
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/spring-security-taglibs-4.2.5.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1522394476000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.5.RELEASE.jar", Long.valueOf(1663548649495L));
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Mango/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Mango/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.16.RELEASE.jar", Long.valueOf(1663548648291L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("mango.mango.model.MemberVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");

MemberVO login = (MemberVO) session.getAttribute("login");

      out.write('\r');
      out.write('\n');

request.setAttribute("id", login.getId());
String id = request.getParameter("id");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/askForm.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"ask_container\">\r\n");
      out.write("      <!-- 1:1문의 폼 -->\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("         <h1 id=\"h_div\">1:1 문의 하기</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <form method=\"post\" action=\"/page/askForm/insert.do\"\r\n");
      out.write("         onsubmit=\"return fnConfirm('y');\">\r\n");
      out.write("         <!-- <div>\r\n");
      out.write("         <div>\r\n");
      out.write("            FAQ를 이용하시면 궁금증을 더 빠르게 해결하실 수 있습니다.<br> 1:1 문의글 답변 운영시간 10:00 ~\r\n");
      out.write("            19:00<br> 접수 후 48시간 안에 답변 드리겠습니다.<br>\r\n");
      out.write("         </div>\r\n");
      out.write("         <ul>\r\n");
      out.write("            <li>고객님고객님의 문의에 답변하는 직원은 고객 여러분의 가족 중 한 사람일 수 있습니다.<br>\r\n");
      out.write("               고객의 언어폭력(비하, 욕설, 협박, 성희롱 등)으로부터 직원을 보호하기 위해 관련 법에 따라 수사기관에 필요한 조치를\r\n");
      out.write("               요구할 수 있으며,<br> 형법에 의해 처벌 대상이 될 수 있습니다.\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>문의하시기 전 FAQ를 확인하시면 궁금증을 더욱 빠르게 해결하실 수 있습니다.</li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div> -->\r\n");
      out.write("\r\n");
      out.write("         <div></div>\r\n");
      out.write("         <!-- 본문 -->\r\n");
      out.write("         <div>\r\n");
      out.write("            <table>\r\n");
      out.write("               <tbody>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td id=\"none\">\r\n");
      out.write("                        <h1 class=\"t_head\">문의 내용</h1>\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th scope=\"row\" class=\"cols1\">분&nbsp;&nbsp;&nbsp;류</th>\r\n");
      out.write("                     <td>\r\n");
      out.write("                     <select title=\"문의 내용 분류 선택\" name=\"askCat\" class=\"selBox\">\r\n");
      out.write("                           <option value=\"0\" selected>분류 선택</option>\r\n");
      out.write("                           <option value=\"영화관\">영화관</option>\r\n");
      out.write("                           <option value=\"영화\">영화</option>\r\n");
      out.write("                           <option value=\"예매/결제\">예매/결제</option>\r\n");
      out.write("                           <option value=\"결제\">이벤트</option>\r\n");
      out.write("                           <option value=\"개인정보\">개인정보</option>\r\n");
      out.write("                           <option value=\"분실물\">분실물</option>\r\n");
      out.write("                     </select> \r\n");
      out.write("                     <select title=\"문의내용 종류\" name=\"askCatDetail\" class=\"selBox\">\r\n");
      out.write("                           <option value=\"0\" selected>문의 종류</option>\r\n");
      out.write("                           <option value=\"문의\">문의</option>\r\n");
      out.write("                           <option value=\"건의\">건의</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th scope=\"row\" class=\"cols1\">종&nbsp;&nbsp;&nbsp;류</th>\r\n");
      out.write("                     <td>\r\n");
      out.write("                        <input type=\"radio\" name=\"rdo00\" id=\"rdo01\" checked>\r\n");
      out.write("                        <label for=\"rdo01\" class=\"rdoT1\">영화관문의</label> \r\n");
      out.write("                           <span> \r\n");
      out.write("                              <select name=\"ask_type\" id=\"askType\" class=\"selBox\" onChange=\"cat1_change(this.value,aks_typeDetail)\">\r\n");
      out.write("                                    <option value=\"0\" selected>영화관 선택</option>\r\n");
      out.write("                                    <option value=\"1\">서울</option>\r\n");
      out.write("                                    <option value=\"2\">경기/인천</option>\r\n");
      out.write("                                    <option value=\"3\">충청/대전</option>\r\n");
      out.write("                                    <option value=\"4\">전라/광주</option>\r\n");
      out.write("                                    <option value=\"5\">경북/대구</option>\r\n");
      out.write("                                    <option value=\"6\">경남/부산/울산</option>\r\n");
      out.write("                                    <option value=\"7\">강원</option>\r\n");
      out.write("                                    <option value=\"8\">제주</option>\r\n");
      out.write("                              </select>\r\n");
      out.write("                              <select name=\"askTypeDetail\" id=\"aks_typeDetail\" class=\"selBox\">\r\n");
      out.write("                                   <option value=\"0\">-선택-</option>\r\n");
      out.write("                              </select>\r\n");
      out.write("                           </span> \r\n");
      out.write("                        <input type=\"radio\" name=\"rdo00\" id=\"rdo02\"> \r\n");
      out.write("                        <label for=\"rdo02\">기타문의</label>\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th scope=\"row\" class=\"cols1\">제&nbsp;&nbsp;&nbsp;목</th>\r\n");
      out.write("                     <td><input type=\"text\" name=\"askSubject\" class=\"textBox\"\r\n");
      out.write("                        placeholder=\"제목을 입력하세요\" title=\"문의 내용 제목 입력\" required>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th scope=\"row\" class=\"cols1\">내&nbsp;&nbsp;&nbsp;용</th>\r\n");
      out.write("                     <td><textarea name=\"askContent\" cols=\"100\" rows=\"10\"\r\n");
      out.write("                           title=\"문의 내용을 입력해 주세요\" required\r\n");
      out.write("                           placeholder=\"내용에 개인정보(카드번호, 계좌번호, 주민번호)가 포함되지 않도록 유의하여 입력해 주세요.\"></textarea>\r\n");
      out.write("                        <!-- 내용 및 첨부파일에 개인정보(카드번호, 계좌번호, 주민번호)가 포함되지 않도록 유의하여 입력해 주세요. -->\r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <!-- <table summary=\"고객정보작성 테이블\"> -->\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <td id=\"none\">\r\n");
      out.write("                           <h1 class=\"t_head\">고객정보</h1>\r\n");
      out.write("                        </td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th csope=\"row\" class=\"cols1\">성&nbsp;&nbsp;&nbsp;명</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"askName\"\r\n");
      out.write("                           placeholder=\"성명을 입력해 주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"cols1\">연락처</th>\r\n");
      out.write("                        <td><input type=\"text\" name=\"askPhone\" title=\"연락처\"\r\n");
      out.write("                           maxlength=\"11\" onkeyup=\"onlyNum(this);\"\r\n");
      out.write("                           placeholder=\"-없이 입력해 주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.getPhone()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                     </tr>\r\n");
      out.write("\r\n");
      out.write("                     <tr>\r\n");
      out.write("                        <th scope=\"row\" class=\"cols1\">이메일</th>\r\n");
      out.write("                        <td><input type=\"email\" name=\"askEmail\"\r\n");
      out.write("                           placeholder=\"이메일을 입력해 주세요\" required > \r\n");
      out.write("                           <span>답변 등록시 해당 이메일로 자동 발송 됩니다.</span></td>\r\n");
      out.write("                              <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.getId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("                     </tr>\r\n");
      out.write("               </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("               <h1 class=\"t_head\" id=\"agree_head\">개인정보 수집에 대한 동의</h1>\r\n");
      out.write("               <div>\r\n");
      out.write("                  <p>문의를 통해 아래의 개인정보를 수집합니다. 수집된 개인정보는 문의 외 목적으로 사용 하지 않습니다.</p>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div>\r\n");
      out.write("                  <textarea cols=\"100\" rows=\"10\" class=\"agreeBox\">\r\n");
      out.write("    * 개인정보의 수집목적 및 항목\r\n");
      out.write("      ① 수집 목적 : 원활한 고객 상담, 불편사항 및 문의사항 관련 의사소통 경로 확보\r\n");
      out.write("      ② 수집 항목\r\n");
      out.write("    *필수입력사항\r\n");
      out.write("     - 이용자 식별을 위한 항목 : 성명, 연락처\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("    * 개인정보의 보유 및 이용기간\r\n");
      out.write("     - 입력하신 개인정보는 소비자 보호에 관한 법률 등 관계 법률에 의해 다음과 같이 보유합니다.\r\n");
      out.write("     - 보유기간 : 문의접수 후 처리 완료시점으로 부터 3년\r\n");
      out.write("   \r\n");
      out.write("    ※ 1:1문의 서비스 제공을 위한 최소한의 개인정보이며 거부할 수 있습니다. \r\n");
      out.write("       다만, 수집에 동의하지 않을 경우 서비스 이용이 제한됩니다.\r\n");
      out.write("                     </textarea>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"rdo1\">\r\n");
      out.write("                  <input type=\"radio\" name=\"rdo01\" value=\"true\" id=\"agreeBtn1\">\r\n");
      out.write("                  <label for=\"radio10\" class=\"rd1\">동의</label> <input type=\"radio\"\r\n");
      out.write("                     name=\"rdo01\" value=\"false\" id=\"agreeBtn2\" checked> <label\r\n");
      out.write("                     for=\"radio11\">동의하지않음</label>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"btn_A\">\r\n");
      out.write("                  <input class=\"btn1\" type=\"reset\" value=\"다시 쓰기\"> <input\r\n");
      out.write("                     class=\"btn2\" type=\"submit\" value=\"접수\">\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   </form>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/askForm.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
